version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  api:
    build: .
    container_name: api
    volumes:
      - .:/go/src
    ports:
      - 8181:8181
